
DROP TABLE IF EXISTS UserStaticInfos
DROP TABLE IF EXISTS Users

CREATE TABLE Users (
	ID INT NOT NULL PRIMARY KEY,
	NICKNAME VARCHAR(16) NOT NULL DEFAULT 'nickname',
	PASSWORD VARCHAR(20) NULL,
	WIN INT NOT NULL DEFAULT 0,
	LOSE INT NOT NULL DEFAULT 0,
	LEVEL INT NOT NULL DEFAULT 1,
	EXP BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE UserStaticInfos (
	ID INT,
	EMAIL VARCHAR(32) NOT NULL UNIQUE,
	
	FOREIGN KEY(ID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO Users ([ID], [NICKNAME], [PASSWORD]) VALUES (100, 'iconer', '1234');
SELECT TOP (1000) * FROM [dbo].[Users]
