CREATE TABLE [dbo].[User]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [NICKNAME] NCHAR(16) NOT NULL DEFAULT 'Name', 
    [PASSWORD] NCHAR(16) NULL, 
    [LEVEL] INT NOT NULL DEFAULT 1, 
    [EXP] BIGINT NOT NULL DEFAULT 0, 
    [WIN] INT NOT NULL DEFAULT 0, 
    [LOSE] INT NOT NULL DEFAULT 0
)
